```{r}
#Imports
library(malecns)
library(coconatfly)
library(fafbseg)
library(neuprintr)
library(ggplot2)
library(dplyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(tidygraph)
library(ggraph)
library(jsonlite)
library(ggplot2)
library(reshape2)
library(Matrix)
library(ggplot2)
library(ggpubr)

#conna = neuprint_login(dataset='male-cns:v0.9',server='https://neuprint-cns.janelia.org/')
#mcns.rois = neuprint_ROIs(dataset = 'male-cns:v0.9')
#neuprint_get_synapses(13693,roi='VNC')
```

```{r setup, include=FALSE}
# Setup knitr global options for clean rendering and consistent figures
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = 'center',
  fig.width = 8,
  fig.height = 6
)
```


## 1 Load data

### 1.1 Load male boday annotations
```{r}
synapse_threshold=5
mba<-mcns_body_annotations()
mba.static<-mcns_body_annotations()
mba<-mba%>%mutate(type=ifelse(type=='',NA,type))
mba <- mba %>%
  mutate(type=coalesce(type,flywire_type,manc_type,hemibrain_type))%>%
  mutate(
    type = case_when(
      grepl("putative_ppk23", receptor_type) ~ "m-cell",
      grepl("putative_ppk25", receptor_type) ~ "f-cell",
      TRUE ~ type
    )
  )%>%
  mutate(cachero.type = str_extract(synonyms, "(?<=Cachero 2010:)[^;]+") %>%
                            str_trim())
```

### 1.2 Function to load connectivity
```{r}
fetch_connectivity <- function(synapse_threshold = 5) {
  mba <- mcns_body_annotations()%>%
    mutate(type=coalesce(type,flywire_type,manc_type,hemibrain_type))%>%
    mutate(cachero.type = str_extract(synonyms, "(?<=Cachero 2010:)[^;]+") %>%
                            str_trim())
  connectivity <- cf_partners(cf_ids(malecns = mba %>% pull(bodyid)),
                              partners = 'o',
                              threshold = synapse_threshold)
  connectivity <- connectivity %>%
    left_join(mba %>%
                select("type", "bodyid",'fru_dsx','consensus_nt','flywire_type','synonyms','receptor_type','cachero.type','dimorphism') %>%
                mutate(bodyid=as.integer(bodyid))%>%
                rename(pre_type = type,pre_fru_dsx=fru_dsx,pre_nt=consensus_nt,pre_fw_type=flywire_type,pre_synonyms=synonyms,pre_receptor_type=receptor_type,pre.dimorphism=dimorphism,pre.cachero.type=cachero.type),
              by = c('pre_id'='bodyid'))%>%
    rename(post_type = type)%>%
    left_join(mba %>%
                select("bodyid",'fru_dsx','consensus_nt','flywire_type','synonyms','receptor_type','cachero.type','dimorphism') %>%
                mutate(bodyid=as.integer(bodyid))%>%
                rename(post_fru_dsx=fru_dsx,post_nt=consensus_nt,post_fw_type=flywire_type,post_synonyms=synonyms,post_receptor_type=receptor_type,post.dimorphism=dimorphism,post.cachero.type=cachero.type),
              by = c('post_id'='bodyid'))
  return(connectivity)
}
```

### 1.3 Load connectivity
```{r}
conn <-fetch_connectivity()
conn_save <- conn

conn <- conn %>%
  mutate(
    pre_type = case_when(
      grepl("putative_ppk23", pre_receptor_type) ~ "m-cell",
      grepl("putative_ppk25", pre_receptor_type) ~ "f-cell",
      TRUE ~ pre_type
    ),
    post_type = case_when(
      grepl("putative_ppk23", post_receptor_type) ~ "m-cell",
      grepl("putative_ppk25", post_receptor_type) ~ "f-cell",
      TRUE ~ post_type
    )
  )
```

## 2 Adjacency matrix
### 2.1 Function adjacency matrix
```{r}
calculate_normed_adj_matrix <-function(connectivity,cell.or.type='type',pre.or.post='pre'){
  colScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::colSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- A %*% Matrix::Diagonal(x = scalefac)
    B
    }
  rowScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::rowSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- Matrix::Diagonal(x = scalefac) %*% A
    B
    }
  if(cell.or.type=='cell'){
    unique.identifier <- union(as.character(connectivity$pre_id), as.character(connectivity$post_id))
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_id, unique.identifier),
      j = match(connectivity$post_id, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }else{
    unique.identifier <- union(connectivity$pre_type, connectivity$post_type)
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_type, unique.identifier),
      j = match(connectivity$post_type, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }
  if(pre.or.post=='pre'){
    adj.matrix.normed.pre <- rowScale(adj.matrix)
    colnames(adj.matrix.normed.pre) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.pre) <- rownames(adj.matrix)
    return(adj.matrix.normed.pre)
  }else if(pre.or.post=='avg'){
    adj.matrix.normed.post <- colScale(adj.matrix)
    colnames(adj.matrix.normed.post) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.post) <- rownames(adj.matrix)
    adj.matrix.normed.pre <- rowScale(adj.matrix)
    colnames(adj.matrix.normed.pre) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.pre) <- rownames(adj.matrix)
    
    return(avg_mat <- (adj.matrix.normed.post + adj.matrix.normed.post) / 2)
    
  }
  
  else{
    adj.matrix.normed.post <- colScale(adj.matrix)
    colnames(adj.matrix.normed.post) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.post) <- rownames(adj.matrix)
    return(adj.matrix.normed.post)
  }
}
```

### 2.1 Create adjacency matrix
```{r}
use.clone <- F
conn<-conn_save
conn<- conn%>%
  mutate(pre_type=coalesce(pre_type,pre_fw_type),post_type=coalesce(post_type,post_fw_type))%>%
  mutate(pre_type=if_else(is.na(pre_type),as.character(bodyid),pre_type),
         post_type=if_else(is.na(post_type),as.character(partner),post_type))%>%
  mutate(pre_type = gsub("[()]", "", pre_type))%>%
  mutate(post_type = gsub("[()]", "", post_type))




#nam <-calculate_normed_adj_matrix(conn.wo.gaba,cell.or.type='type',pre.or.post='avg') #avg
nam <-calculate_normed_adj_matrix(conn,cell.or.type='type',pre.or.post='post') #avg
nam_thresholded <-nam

g.prout.mcns <- graph_from_adjacency_matrix(
  nam_thresholded,
  mode = "directed",
  weighted = TRUE,
  diag = FALSE
)
```

#Examples vAB3 (11998)
```{r}

  inputs.11998 <- mcns_connection_table(11998,partners='inputs')
  inputs.11998.sum <- inputs.11998%>%group_by(type)%>%summarize(weight=sum(weight))
  inputs.11998.sum$post.input.normed <- inputs.11998.sum$weight/sum(inputs.11998$weight)
  inputs.11998.sum<- inputs.11998.sum %>%
    rename(pre=type)%>%
    mutate(IR52b = pre %in% IR52b.types,
          IR52a = pre %in% IR52a.types,
          ppk25 = pre %in% ppk25.types,
          ppk23 = pre %in% ppk23.types,
          post='vAB3 (11998)') %>% 
    
    left_join(mba.dimorphism,by= c('pre'='type'))
  
  outputs.11998 <- mcns_connection_table(11998,partners='outputs')
  outputs.11998.sum <- outputs.11998%>%group_by(type)%>%summarize(weight=sum(weight))
  outputs.11998.sum$post.input.normed <- outputs.11998.sum$weight/sum(inputs.11998$weight)
  outputs.11998.sum<- outputs.11998.sum %>%
    rename(post=type)%>%
    mutate(IR52b = FALSE,
          IR52a = FALSE,
          ppk25 = FALSE,
          ppk23 = FALSE,
          pre='vAB3 (11998)') %>% 
    
    left_join(mba.dimorphism,by= c('post'='type'))
  
  in.and.out.11998 <- rbind(inputs.11998.sum,outputs.11998.sum)
  
```

#Examples PPN1 (11431)
```{r}

  inputs.11431 <- mcns_connection_table(11431,partners='inputs')
  inputs.11431.sum <- inputs.11431%>%group_by(type)%>%summarize(weight=sum(weight))
  inputs.11431.sum$post.input.normed <- inputs.11431.sum$weight/sum(inputs.11998$weight)
  inputs.11431.sum<- inputs.11431.sum %>%
    rename(pre=type)%>%
    mutate(IR52b = pre %in% IR52b.types,
          IR52a = pre %in% IR52a.types,
          ppk25 = pre %in% ppk25.types,
          ppk23 = pre %in% ppk23.types,
          post='PPN1 (11431)') %>% 
    left_join(mba.dimorphism,by= c('pre'='type'))
  
  outputs.11431 <- mcns_connection_table(11431,partners='outputs')
  outputs.11431.sum <- outputs.11431%>%group_by(type)%>%summarize(weight=sum(weight))
  outputs.11431.sum$post.input.normed <- outputs.11431.sum$weight/sum(inputs.11998$weight)
  outputs.11431.sum<- outputs.11431.sum %>%
    rename(post=type)%>%
    mutate(IR52b = FALSE,
          IR52a = FALSE,
          ppk25 = FALSE,
          ppk23 = FALSE,
          pre='PPN1 (11431)') %>% 
    left_join(mba.dimorphism,by= c('post'='type'))
  
  in.and.out.11431 <- rbind(inputs.11431.sum,outputs.11431.sum)
  
```

target cells PPN1 and vAB3
```{r}
cutoff=0.1
target.PPN1 <- in.and.out %>%
    filter(post %in% setdiff(outputs.11431.sum%>%pull(post),outputs.11998.sum%>%pull(post)))%>%
    filter(!grepl('AN',post)) %>% 
    filter(!grepl('IN',post)) %>% 
    filter(weight>=100)%>%pull(post)

target.vAB3 <- in.and.out %>%
    filter(post %in% setdiff(outputs.11998.sum%>%pull(post),outputs.11431.sum%>%pull(post)))%>%
    filter(weight>=100)%>%
    filter(!grepl('AN',post)) %>% 
    filter(!grepl('IN',post)) %>% 
    pull(post)
```

define kstrongest path function
```{r}
# Requires: igraph, dplyr
find_k_strongest_paths <- function(
  g,
  starts,
  targets,
  n_paths = 3,
  diversity = c("otheredges","othernodes","none")
){
  diversity <- match.arg(diversity)

  # weights → log-costs; guard zeros/NAs
  w <- E(g)$weight
  if (is.null(w)) stop("Edges must have numeric 'weight'.")
  w[!is.finite(w) | w <= 0] <- .Machine$double.eps
  log_w <- -log(w)

  results <- list()
  all_nodes <- character(0)

  for (s in starts) for (t in targets) {
    if (!(s %in% V(g)$name) || !(t %in% V(g)$name)) {
      results[[paste(s,t,sep="->")]] <- list(list(
        start = s, end = t, path = NA_character_, strength = NA_real_, hops = NA_integer_
      ))
      next
    }

    g_tmp <- g
    E(g_tmp)$log_weight <- log_w
    pair_paths <- list()

    for (i in seq_len(n_paths)) {
      sp <- igraph::shortest_paths(
        g_tmp, from = s, to = t,
        weights = E(g_tmp)$log_weight,
        output = "both"
      )
      if (length(sp$vpath[[1]]) == 0) break

      vpath <- sp$vpath[[1]]
      epath <- sp$epath[[1]]

      final_strength <- exp(-sum(E(g_tmp)[epath]$log_weight))
      hops <- length(epath)

      pair_paths[[paste0("path", i)]] <- list(
        start = s,
        end = t,
        path = paste(V(g)[vpath]$name, collapse = " -> "),
        strength = final_strength,
        hops = hops
      )

      all_nodes <- c(all_nodes, V(g)[vpath]$name)

      if (diversity == "othernodes") {
        inter <- setdiff(V(g)[vpath]$name, c(s, t))
        if (length(inter)) g_tmp <- igraph::delete_vertices(g_tmp, inter)
      } else if (diversity == "otheredges") {
        g_tmp <- igraph::delete_edges(g_tmp, epath)
      }
    }

    results[[paste(s,t,sep="->")]] <- pair_paths
  }

  # flatten
  results_df <- do.call(rbind, lapply(results, function(pl) {
    do.call(rbind, lapply(pl, function(r)
      data.frame(start=r$start, end=r$end, path=r$path,
                 strength=r$strength, hops=r$hops,
                 stringsAsFactors=FALSE)))
  }))

  results_df_wo_na <- dplyr::filter(results_df, !is.na(strength))
  all_nodes <- unique(all_nodes)

  list(df = results_df_wo_na, nodes = all_nodes, raw = results)
}

```




path finding new


```{r}
#olfactory
start.types.olf <- c('ORN_DA1','ORN_VA1v')
res.vAB3.olf <- find_k_strongest_paths(g.prout.mcns, starts=start.types.olf, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.olf <- find_k_strongest_paths(g.prout.mcns, starts=start.types.olf, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.olf$df$dataset <- "vAB3"
res.PPN1.olf$df$dataset <- "PPN1"
df_all.olf <- bind_rows(res.vAB3.olf$df, res.PPN1.olf$df)



t_res  <- t.test(strength ~ dataset, data = df_all.olf)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.olf$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.olf, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength Visual") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 



ggplot(df_all.olf, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path Olfactory") +
  theme(plot.title = element_text(hjust = 0.5))


#visual
start.types.vis <- mba%>%filter(superclass=='ol_sensory')%>%pull(type)%>%unique()
res.vAB3.vis <- find_k_strongest_paths(g.prout.mcns, starts=start.types.vis, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.vis <- find_k_strongest_paths(g.prout.mcns, starts=start.types.vis, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.vis$df$dataset <- "vAB3"
res.PPN1.vis$df$dataset <- "PPN1"
df_all.vis <- bind_rows(res.vAB3.vis$df, res.PPN1.vis$df)
t_res  <- t.test(strength ~ dataset, data = df_all.vis)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.vis$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.vis, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength Visual") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 

ggplot(df_all.vis, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path Visual") +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
#contact chemosensor ppk23

start.types.ppk23 <- mba.static%>%filter(grepl('ppk23',receptor_type))%>%pull(type)%>%unique()
res.vAB3.ppk23 <- find_k_strongest_paths(g.prout.mcns, starts=start.types.ppk23, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.ppk23 <- find_k_strongest_paths(g.prout.mcns, starts=start.types.ppk23, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.ppk23$df$dataset <- "vAB3"
res.PPN1.ppk23$df$dataset <- "PPN1"
df_all.ppk23 <- bind_rows(res.vAB3.ppk23$df, res.PPN1.ppk23$df) %>%
  filter(!(grepl("AN05B102", path) | grepl("AN09B017", path)))
t_res  <- t.test(strength ~ dataset, data = df_all.ppk23)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.ppk23$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.ppk23, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength ppk23") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 

ggplot(df_all.ppk23, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path ppk23") +
  theme(plot.title = element_text(hjust = 0.5))


#contact chemosensor ppk25

start.types.ppk25 <- mba.static%>%filter(grepl('ppk25',receptor_type))%>%pull(type)%>%unique()
res.vAB3.ppk25 <- find_k_strongest_paths(g.prout.mcns, starts=start.types.ppk25, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.ppk25 <- find_k_strongest_paths(g.prout.mcns, starts=start.types.ppk25, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.ppk25$df$dataset <- "vAB3"
res.PPN1.ppk25$df$dataset <- "PPN1"
df_all.ppk25 <- bind_rows(res.vAB3.ppk25$df, res.PPN1.ppk25$df) %>%
  filter(!(grepl("AN05B102", path) | grepl("AN09B017", path)))
t_res  <- t.test(strength ~ dataset, data = df_all.ppk25)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.ppk25$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.ppk25, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength ppk25") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 

ggplot(df_all.ppk25, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path ppk25") +
  theme(plot.title = element_text(hjust = 0.5))

```

All Neurons downstream

```{r}

all.PPN1.ids <- mba%>%filter(grepl('PPN1',notes))
all.vAB3.ids <- mba%>%filter(grepl('vAB3 Clowney',notes))
target.vAB3.all <- 






#olfactory
start.types.olf <- c('ORN_DA1','ORN_VA1v')
res.vAB3.olf <- find_k_strongest_paths(g.prout.mcns, starts=start.types.olf, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.olf <- find_k_strongest_paths(g.prout.mcns, starts=start.types.olf, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.olf$df$dataset <- "vAB3"
res.PPN1.olf$df$dataset <- "PPN1"
df_all.olf <- bind_rows(res.vAB3.olf$df, res.PPN1.olf$df)



t_res  <- t.test(strength ~ dataset, data = df_all.olf)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.olf$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.olf, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength Visual") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 



ggplot(df_all.olf, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path Olfactory") +
  theme(plot.title = element_text(hjust = 0.5))


#visual
start.types.vis <- mba%>%filter(superclass=='ol_sensory')%>%pull(type)%>%unique()
res.vAB3.vis <- find_k_strongest_paths(g.prout.mcns, starts=start.types.vis, targets=target.vAB3 ,n_paths=3,diversity='otheredges')
res.PPN1.vis <- find_k_strongest_paths(g.prout.mcns, starts=start.types.vis, targets=target.PPN1,n_paths=3,diversity='otheredges')

res.vAB3.vis$df$dataset <- "vAB3"
res.PPN1.vis$df$dataset <- "PPN1"
df_all.vis <- bind_rows(res.vAB3.vis$df, res.PPN1.vis$df)
t_res  <- t.test(strength ~ dataset, data = df_all.vis)
pval   <- unname(t_res$p.value)
ann <- data.frame(
  group1      = "PPN1",
  group2      = "vAB3",
  p           = pval,
  y.position  = max(df_all.vis$strength, na.rm = TRUE) * 1.12
)

ggplot(df_all.vis, aes(x = dataset, y = strength)) +
  geom_boxplot(outlier.shape = NA, fill = "lightgray") +
  geom_jitter(width = 0.2, height = 0, alpha = 0.4, color = "blue") +
  theme_bw() +
  labs(title = "Path strength Visual") +
  theme(plot.title = element_text(hjust = 0.5)) +
  stat_pvalue_manual(
    ann,
    label = "p",         # use the column 'p'
    tip.length = 0
  )+
  scale_y_log10() 

ggplot(df_all.vis, aes(x = dataset, y = hops)) +
  geom_jitter(width = 0.2, height = 0, alpha = 0.6) +
  scale_y_log10() +
  theme_bw()+
  labs(title = "Hops in strongest path Visual") +
  theme(plot.title = element_text(hjust = 0.5))
```




Open graph in RCy3

```{r}
library(RCy3)
library(dplyr)
library(stringr)

# Define nodes of interest
nodes_to_keep <- c("JO-B", "JO-B", "CB1078", "CB1542", "CB2108", "CB1383", "CB1066,CB3649",
                   "CB2364", "CB3382", "PVLP033", "CB3162", "CB3382", "vpoEN", "SIP124m",
                   "AVLP721m", "AVLP299_c", "DNp55", "CB1385", "AVLP711m", "SIP108m", 
                   "SIP120m", "SIP116m", "SIP114m", "PVLP211m", "pMP2", "AVLP744m")

in.plots <- c("vPN1", "aPN1", "aPN1_like", "vpoEN", "vpoIN", "pIP10", "pMP2", "JO-B")
P1_2_add <- conn%>%
  filter(pre_type %in% nodes_to_keep,
         grepl("^P1_", post_type))%>%
  pull(post_type)%>%
  unique()


nodes_to_keep <- c(unique(all_important_nodes), in.plots,P1_2_add)
nodes_to_keep <- c(unique(all_important_nodes))
#nodes_to_keep <- c('pMP2','aPN1_like','pIP10','aIP-g','aDT-e','pIP-e','vpoEN','aPN1','P1_14a','JO-B','WED118','aDT-g','aSP-a','aSP-k','vpoIN','vPN1','P1_6a','DNp55')



#nodes_to_keep <- c(nodes_to_keep,conn%>%filter(post_type=='IN06B003')%>%filter(grepl('SN',pre_type))%>%pull(pre_type)%>%unique())
#nodes_to_keep <- c(nodes_to_keep,mba%>%filter(grepl('TN1a',type))%>%pull(type)%>%unique())
#nodes_to_keep <- c(nodes_to_keep,in.plots,mba%>%filter(grepl('vPR9',type))%>%pull(type)%>%unique())



# Subset the graph
g.sub.prout.mcns <- induced_subgraph(g.prout.mcns, vids = V(g.prout.mcns)[name %in% nodes_to_keep])

# Shortest path distances from start_types
node_names <- V(g.sub.prout.mcns)$name
distance_to_start <- shortest.paths(g.sub.prout.mcns, to = V(g.sub.prout.mcns)[name %in% cell_types], weights = NA)
V(g.sub.prout.mcns)$distance_to_start <- ifelse(node_names %in% cell_types, 0, as.integer(distance_to_start))

# FRU/DSX metadata
try(fru_dsx_values <- conn %>%
      group_by(pre_type, post_type) %>%
      mutate(pre_fru_dsx = !is.na(pre_fru_dsx),
             post_fru_dsx = !is.na(post_fru_dsx)) %>%
      summarize(pre_fru_dsx = first(pre_fru_dsx),
                post_fru_dsx = first(post_fru_dsx)) %>%
      ungroup() %>%
      pivot_longer(cols = c(pre_fru_dsx, post_fru_dsx, pre_type, post_type),
                   names_to = c("side", ".value"), names_sep = "_") %>%
      select(-side) %>% distinct())

# NT metadata
# Helper function: majority vote (mode), returns first mode if tie
majority_vote <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) return(NA)
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

# Compute majority NT per pre_type and post_type
nt_values <- conn %>%
  group_by(pre_type, post_type) %>%
  summarize(
    pre_nt = majority_vote(pre_nt),
    post_nt = majority_vote(post_nt),
    .groups = "drop"
  ) %>%
  pivot_longer(cols = c(pre_nt, post_nt, pre_type, post_type),
               names_to = c("side", ".value"),
               names_sep = "_") %>%
  select(-side) %>%
  distinct()




# Match metadata to vertices
nt_for_vertices <- nt_values$nt[match(V(g.sub.prout.mcns)$name, nt_values$type)]
V(g.sub.prout.mcns)$nt <- nt_for_vertices

#NT for edges
el <- as_edgelist(g.sub.prout.mcns)
edge_sources <- el[, 1]

# Create named vector manually instead of using deframe
nt_table <- nt_values %>%
  distinct(type, nt) %>%
  filter(!is.na(nt))

nt_lookup <- setNames(nt_table$nt, nt_table$type)

# Assign NT to each edge by matching the source node name to nt_lookup
E(g.sub.prout.mcns)$edge_nt <- nt_lookup[edge_sources]

# Optionally fill NAs
E(g.sub.prout.mcns)$edge_nt[is.na(E(g.sub.prout.mcns)$edge_nt)] <- "unknown"

dimorphism_values <- conn %>%
  group_by(pre_type, post_type) %>%
  summarize(
    pre_dimorphism = majority_vote(pre.dimorphism),
    post_dimorphism = majority_vote(post.dimorphism),
    .groups = "drop"
  ) %>%
  pivot_longer(cols = c(pre_dimorphism, post_dimorphism, pre_type, post_type),
               names_to = c("side", ".value"),
               names_sep = "_") %>%
  select(-side) %>%
  distinct()

dimorphism_lookup <- setNames(dimorphism_values$dimorphism, dimorphism_values$type)
V(g.sub.prout.mcns)$dimorphism <- dimorphism_lookup[V(g.sub.prout.mcns)$name]
V(g.sub.prout.mcns)$dimorphism[is.na(V(g.sub.prout.mcns)$dimorphism)] <- "ismorphic"



# P1-P1 flag
el <- as_edgelist(g.sub.prout.mcns)
is_p1p1 <- grepl("^P1_", el[, 1])
E(g.sub.prout.mcns)$is_p1_p1 <- is_p1p1

# Scale weights
E(g.sub.prout.mcns)$weight <- E(g.sub.prout.mcns)$weight * 100

# --- Dynamic quantile-based binning for weights > 1 ---
weights_all <- E(g.sub.prout.mcns)$weight
weights_above_1 <- weights_all[weights_all > 1]

# Compute quantiles and round nicely for legend clarity
quantile_breaks <- quantile(weights_above_1, probs = c(0, 0.25, 0.5, 0.75, 1), na.rm = TRUE)
rounded_breaks <- unique(round(quantile_breaks,2))  # ensure no duplicated breaks

# Handle edge case: fewer than 5 unique bins
if (length(rounded_breaks) < 5) {
  rounded_breaks <- pretty(weights_above_1, n = 4)
}

# Assign bin index
E(g.sub.prout.mcns)$arrow_class <- cut(
  weights_all,
  breaks = rounded_breaks,
  include.lowest = TRUE,
  labels = FALSE
)

# Optional: create human-readable bin label
labels <- paste(head(rounded_breaks, -1), tail(rounded_breaks, -1), sep = "–")
E(g.sub.prout.mcns)$arrow_class_label <- labels[E(g.sub.prout.mcns)$arrow_class]

# Assign 0 and "0" for weights <= 1
E(g.sub.prout.mcns)$arrow_class[weights_all <= 1] <- 0
E(g.sub.prout.mcns)$arrow_class_label[weights_all <= 1] <- "≤1"

# Create network in Cytoscape
RCy3::createNetworkFromIgraph(g.sub.prout.mcns)
```

## Adjacency matrix
```{r}
p1p1_edges <- E(g.sub.prout.mcns)[is_p1p1]
g.sub.prout.mcns.wo.P1P1 <- delete_edges(g.sub.prout.mcns, p1p1_edges)
adj_matrix <- as_adjacency_matrix(g.sub.prout.mcns.wo.P1P1, attr = "weight", sparse = FALSE)
adj_matrix[is.na(adj_matrix)] <- 0
adj_matrix[is.nan(adj_matrix)] <- 0
adj_matrix[is.infinite(adj_matrix)] <- 0
nonzero_cols <- which(colSums(adj_matrix) != 0)
nonzero_rows <- which(rowSums(adj_matrix) != 0)
adj_matrix <- adj_matrix[nonzero_rows, nonzero_cols]
#adj_matrix <- adj_matrix[colnames(adj_matrix)[grepl("P1_*",colnames(adj_matrix))]]

library(pheatmap)
pheatmap(
  adj_matrix,
  scale = "row",                     # Normalize rows (or "column" / "none")
  clustering_distance_rows = "euclidean",
  clustering_distance_cols = "euclidean",
  clustering_method = "complete",   # or "average", "ward.D", etc.
  color = colorRampPalette(c("blue", "white", "red"))(50), # Custom color scale
  main = "vPN1 P1 connectivity",
  fontsize_row = 6,
  fontsize_col = 6,
  cellwidth = 6,
  cellheight = 6
)

```