---
title: "intherited.connectivity"
output: html_document
---

```{r}
#Imports
library(malecns)
library(coconatfly)
library(fafbseg)
library(neuprintr)

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(tidygraph)
library(ggraph)
library(jsonlite)
library(ggplot2)
library(reshape2)
library(Matrix)
library(RCy3)
library(dplyr)

#conna = neuprint_login(dataset='male-cns:v0.9',server='https://neuprint-cns.janelia.org/')
#mcns.rois = neuprint_ROIs(dataset = 'male-cns:v0.9')
#neuprint_get_synapses(13693,roi='VNC')
```

```{r setup, include=FALSE}
# Setup knitr global options for clean rendering and consistent figures
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = 'center',
  fig.width = 8,
  fig.height = 6
)
```


## 1 Load data

### 1.1 Load male boday annotations
```{r}

snapshot=neuprintr::neuprint_login(server='https://neuprint-cns.janelia.org/', dataset="male-cns:v0.9")
malevnc::choose_flyem_dataset('male-cns:v0.9')
synapse_threshold=5
mba<-mcns_body_annotations()
mba.static<-mcns_body_annotations()
mba<-mba%>%mutate(type=ifelse(type=='',NA,type))

ppk23.types <- mba%>%filter(receptor_type=='putative_ppk23')%>%pull(type)%>%unique()
ppk25.types <- mba%>%filter(receptor_type=='putative_ppk25')%>%pull(type)%>%unique()
IR52a.types <- mba%>%filter(receptor_type=='putative_IR52a')%>%pull(type)%>%unique()
IR52b.types <- mba%>%filter(receptor_type=='putative_IR52b')%>%pull(type)%>%unique()


mba.dimorphism <- mba %>%
  count(type, dimorphism) %>%
  group_by(type) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  select(type, dimorphism)


```

#Examples vAB3 (11998)
```{r}

  inputs.11998 <- mcns_connection_table(11998,partners='inputs')
  inputs.11998.sum <- inputs.11998%>%group_by(type)%>%summarize(weight=sum(weight))
  inputs.11998.sum$post.input.normed <- inputs.11998.sum$weight/sum(inputs.11998$weight)
  inputs.11998.sum<- inputs.11998.sum %>%
    rename(pre=type)%>%
    mutate(IR52b = pre %in% IR52b.types,
          IR52a = pre %in% IR52a.types,
          ppk25 = pre %in% ppk25.types,
          ppk23 = pre %in% ppk23.types,
          post='vAB3 (11998)') %>% 
    
    left_join(mba.dimorphism,by= c('pre'='type'))
  
  outputs.11998 <- mcns_connection_table(11998,partners='outputs')
  outputs.11998.sum <- outputs.11998%>%group_by(type)%>%summarize(weight=sum(weight))
  outputs.11998.sum$post.input.normed <- outputs.11998.sum$weight/sum(inputs.11998$weight)
  outputs.11998.sum<- outputs.11998.sum %>%
    rename(post=type)%>%
    mutate(IR52b = FALSE,
          IR52a = FALSE,
          ppk25 = FALSE,
          ppk23 = FALSE,
          pre='vAB3 (11998)') %>% 
    
    left_join(mba.dimorphism,by= c('post'='type'))
  
  in.and.out.11998 <- rbind(inputs.11998.sum,outputs.11998.sum)
  
```

#Examples PPN1 (11431)
```{r}

  inputs.11431 <- mcns_connection_table(11431,partners='inputs')
  inputs.11431.sum <- inputs.11431%>%group_by(type)%>%summarize(weight=sum(weight))
  inputs.11431.sum$post.input.normed <- inputs.11431.sum$weight/sum(inputs.11998$weight)
  inputs.11431.sum<- inputs.11431.sum %>%
    rename(pre=type)%>%
    mutate(IR52b = pre %in% IR52b.types,
          IR52a = pre %in% IR52a.types,
          ppk25 = pre %in% ppk25.types,
          ppk23 = pre %in% ppk23.types,
          post='PPN1 (11431)') %>% 
    left_join(mba.dimorphism,by= c('pre'='type'))
  
  outputs.11431 <- mcns_connection_table(11431,partners='outputs')
  outputs.11431.sum <- outputs.11431%>%group_by(type)%>%summarize(weight=sum(weight))
  outputs.11431.sum$post.input.normed <- outputs.11431.sum$weight/sum(inputs.11998$weight)
  outputs.11431.sum<- outputs.11431.sum %>%
    rename(post=type)%>%
    mutate(IR52b = FALSE,
          IR52a = FALSE,
          ppk25 = FALSE,
          ppk23 = FALSE,
          pre='PPN1 (11431)') %>% 
    left_join(mba.dimorphism,by= c('post'='type'))
  
  in.and.out.11431 <- rbind(inputs.11431.sum,outputs.11431.sum)
  
```



```{r}
# --- Cytoscape export (RCy3) ---

library(RCy3)
library(dplyr)

# Combine (you already have in.and.out.11431, in.and.out.11998)
# NOTE: fix a likely typo above: use inputs.11431.sum, not inputs.11431, when creating in.and.out.11431
# in.and.out.11431 <- rbind(inputs.11431.sum, outputs.11431.sum)

in.and.out <- bind_rows(in.and.out.11431, in.and.out.11998)

# Edges: directed pre -> post
edges.df <- in.and.out %>%
  transmute(source = pre,
            target = post,
            weight = weight,
            post.input.normed = post.input.normed)

# Nodes: carry attributes from both pre and post sides, coalesced
pre.nodes  <- in.and.out %>%
  select(id = pre, IR52b, IR52a, ppk25, ppk23, dimorphism) %>%
  distinct()

post.nodes <- in.and.out %>%
  select(id = post, IR52b, IR52a, ppk25, ppk23, dimorphism) %>%
  distinct()

nodes.df <- full_join(pre.nodes, post.nodes, by = "id", suffix = c(".pre", ".post")) %>%
  mutate(
    IR52b = coalesce(IR52b.pre, IR52b.post),
    IR52a = coalesce(IR52a.pre, IR52a.post),
    ppk25 = coalesce(ppk25.pre, ppk25.post),
    ppk23 = coalesce(ppk23.pre, ppk23.post),
    dimorphism = coalesce(dimorphism.pre, dimorphism.post)
  ) %>%
  select(id, IR52b, IR52a, ppk25, ppk23, dimorphism)

# Create/replace network
net.suid <- createNetworkFromDataFrames(
  nodes = nodes.df,
  edges = edges.df,
  title = "vAB3_11998__PPN1_11431_inputs_outputs",
  collection = "InheritedConnectivity"
)




```


#FIND DIFFERENCE

```{r}

in.and.out %>%
  filter(post %in% setdiff(outputs.11431.sum%>%pull(post),outputs.11998.sum%>%pull(post)))%>%
  filter(weight>=5)%>%
  View()


in.and.out %>%
  filter(post %in% setdiff(outputs.11998.sum%>%pull(post),outputs.11431.sum%>%pull(post)))%>%
  filter(weight>=5)%>%
  View()


```

